Proyecto Integrador - Minería de Datos I
Notebook 1: Inspección Inicial del Dataset **texto en negrita**

Paso 1 - Importar las librerías

In [ ]:
# Importar librerías

import pandas as pd
import numpy as np

# Mostrar todas las columnas del DataFrame

pd.set_option("display.max_columns", None)

Paso 2 - Cargar el archivo JSON

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving streaming_users_dirty.json to streaming_users_dirty.json

Paso 3 - Leer el archivo

In [ ]:
df = pd.read_json("streaming_users_dirty.json")

df.head()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1

Paso 4 - Visualizar los primeros registros

In [ ]:
df.head()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1

Paso 5 - Visualizar los últimos registros

In [ ]:
df.tail()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
8155,10923,23,Premium,1161.4,Colombia,Romance,2023-05-15,0
8156,16525,27,Básico,436.2,Uruguay,Documental,2018-09-06,4
8157,11222,13,Estándar,1321.8,México,Documental,2019-02-08,0
8158,15613,38,Estándar,835.7,Brasil,Drama,2022-02-05,0
8159,16912,25,Estándar,1468.7,Argentina,Romance,2022-08-12,3

Paso 6 - Conocer las dimensiones del dataset

In [ ]:
print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

Cantidad de filas: 8160
Cantidad de columnas: 8

Paso 7 - Información general del dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8160 entries, 0 to 8159
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8160 non-null   int64
 1   age                       8160 non-null   int64
 2   subscription_plan         8160 non-null   object
 3   monthly_watch_time_mins   7967 non-null   float64
 4   country                   8160 non-null   object
 5   favorite_genre            7920 non-null   object
 6   last_login_date           7840 non-null   object
 7   customer_support_tickets  8160 non-null   int64
dtypes: float64(1), int64(3), object(4)
memory usage: 510.1+ KB

Paso 8 - Mostrar el nombre de las columnas

In [ ]:
print(df.columns)

Index(['user_id', 'age', 'subscription_plan', 'monthly_watch_time_mins',
       'country', 'favorite_genre', 'last_login_date',
       'customer_support_tickets'],
      dtype='object')

Paso 9 - Revisar los tipos de datos

In [ ]:
print(df.dtypes)

user_id                       int64
age                           int64
subscription_plan            object
monthly_watch_time_mins     float64
country                      object
favorite_genre               object
last_login_date              object
customer_support_tickets      int64
dtype: object

Paso 10 - Estadísticas descriptivas

In [ ]:
df.describe()

,user_id,age,monthly_watch_time_mins,customer_support_tickets
count,8160.000000,8160.000000,7967.000000,8160.000000
mean,13995.433824,34.096814,1107.346153,1.800980
std,2310.810660,14.511304,5310.442604,11.334969
min,10000.000000,-5.000000,-120.000000,-1.000000
25%,11987.750000,25.000000,489.200000,0.000000
50%,13998.500000,33.000000,757.400000,1.000000
75%,15997.250000,42.000000,1045.700000,1.000000
max,17999.000000,150.000000,99999.000000,150.000000

Paso 11 - Variables categóricas

In [ ]:
df.describe(include="object")

       subscription_plan country favorite_genre last_login_date
count               8160    8160           7920            7840
unique                15      26             28            3062
top               Básico  Brasil        Comedia      2026-15-03
freq                3450    1132           1112              20

Paso 12 - Buscar valores faltantes

In [ ]:
df.isnull().sum()

user_id                       0
age                           0
subscription_plan             0
monthly_watch_time_mins     193
country                       0
favorite_genre              240
last_login_date             320
customer_support_tickets      0
dtype: int64

Paso 13 - Buscar registros duplicados

In [ ]:
print("Cantidad de registros duplicados:", df.duplicated().sum())

Cantidad de registros duplicados: 126

Paso 14 - Contar valores únicos

In [ ]:
df.nunique()

user_id                     8000
age                           69
subscription_plan             15
monthly_watch_time_mins     5788
country                       26
favorite_genre                28
last_login_date             3062
customer_support_tickets       9
dtype: int64

Paso 15 - Revisar las variables categóricas

In [ ]:
for columna in df.select_dtypes(include="object").columns:
    print("\n------------------------------")
    print("Columna:", columna)
    print(df[columna].unique())

------------------------------
Columna: subscription_plan
['Estándar' 'Básico' 'Premium' 'Std' 'estandar' 'basico' 'básico'
 'Premium ' 'premium' 'Premiun' 'BASICO' 'STANDARD' 'Basic' 'Estándar '
 'PREMIUM']

------------------------------
Columna: country
['Brasil' 'Colombia' 'Uruguay' 'Perú' 'Chile' 'Argentina' 'México'
 'Brazil' 'brasil' 'méxico' 'chile' 'uruguay' 'MEX' 'ARG' 'colombia' 'COL'
 'Mexico' 'URY' 'Chile ' 'Peru' 'perú' 'argentina' 'PER' 'Argentina '
 'BRA' 'CHL']

------------------------------
Columna: favorite_genre
['Crime' 'Thriller' 'Drama' 'Acción' 'Romance' 'Comedia' 'Documental'
 'ACCIÓN' None 'CRIME' 'Comedia ' 'comedy' 'DRAMA' 'THRILLER'
 'Documentary' 'Thriller ' 'accion' 'Action' 'COMEDIA' 'ROMANCE' 'thriler'
 'DOC' 'romance' 'Crimen' 'Drama ' 'drama' 'Romance ' 'documental' 'crime']

------------------------------
Columna: last_login_date
['2025-03-04' '2019-04-02' '2018-04-13' ... '2018-06-25' '2019/04/30'
 '2025-07-19']

Paso 16 - Frecuencia de las categorías

In [ ]:
for columna in df.select_dtypes(include="object").columns:
    print("\n==============================")
    print("Columna:", columna)
    print(df[columna].value_counts())

==============================
Columna: subscription_plan
subscription_plan
Básico       3450
Estándar     2711
Premium      1519
basico         60
BASICO         52
Basic          52
básico         50
Std            48
Estándar       46
estandar       36
STANDARD       34
Premium        31
PREMIUM        26
Premiun        23
premium        22
Name: count, dtype: int64

==============================
Columna: country
country
Brasil        1132
Chile         1132
México        1129
Uruguay       1124
Perú          1120
Colombia      1116
Argentina     1087
colombia        27
méxico          25
uruguay         24
Brazil          21
COL             19
CHL             18
URY             17
argentina       16
MEX             16
Chile           16
PER             16
Peru            15
BRA             15
chile           15
Mexico          15
brasil          13
perú            12
ARG             10
Argentina       10
Name: count, dtype: int64

==============================
Columna: favorite_genre
favorite_genre
Comedia        1112
Drama          1105
Documental     1095
Thriller       1090
Romance        1090
Acción         1082
Crime          1067
Action           22
COMEDIA          19
Crimen           18
Romance          17
CRIME            17
Documentary      16
DRAMA            16
Comedia          15
DOC              15
ROMANCE          14
ACCIÓN           14
THRILLER         14
comedy           12
Thriller         12
romance          12
documental       10
drama            10
accion            8
Drama             7
thriler           6
crime             5
Name: count, dtype: int64

==============================
Columna: last_login_date
last_login_date
2026-15-03       20
0000-00-00       17
2029-01-01       15
not_available    14
31-02-2022       13
                 ..
2018-11-07        1
2022-03-20        1
2019-01-19        1
2018-05-03        1
2024-02-12        1
Name: count, Length: 3062, dtype: int64

 Paso 17 - Observaciones iniciales

In [ ]:
print("Inspección inicial finalizada correctamente.")

Inspección inicial finalizada correctamente.

In [ ]:
# Conclusiones de la inspección inicial

La exploración inicial permitió conocer la estructura general del conjunto de datos y detectar posibles aspectos que deberán analizarse en la siguiente etapa del proyecto.

Entre las observaciones más relevantes se encuentran la presencia de valores faltantes, posibles registros duplicados, categorías con diferencias de escritura y variables que requerirán una revisión más detallada. Estos resultados servirán como evidencia para justificar las decisiones de limpieza y preparación de los datos en el siguiente notebook.

En esta etapa no se realizaron modificaciones sobre el dataset original, cumpliendo con el objetivo de efectuar únicamente una inspección preliminar.