In [25]:
# Inspección inicial del dataset

## Proyecto Integrador - Minería de Datos I

### Objetivo

# En este notebook se realizo 15 pasos en los cuales se trabajo para ver todos los datos,que contiene ,si esta limpio y si hay registros duplicados.

Paso 1 Importamos todas las librerias que vamos a utilizar

In [4]:
# Importar librerías
import pandas as pd
import numpy as np

# Mostrar todas las columnas
pd.set_option('display.max_columns', None)

Paso 2 cargamos el datasets

In [7]:
# Cargar el dataset
df = pd.read_csv("/content/reporte_clinica.csv")

Paso 3 Visualizamos los primeros registros

In [8]:
df.head()

   Unnamed: 0   age     sex     bmi  children smoker     region      charges
0           0  19.0  female  27.900         0    yes  southwest  16884.92400
1           1  18.0    male  33.770         1     no         SE   1725.55230
2           2  28.0    male  33.000         3     no  southeast   4449.46200
3           3  33.0    male  22.705         0     no  northwest  21984.47061
4           4  32.0    male  28.880         0     no  northwest   3866.85520

Paso 4 visualizamos los ultimos registros

In [9]:
df.tail()

,Unnamed: 0,age,sex,bmi,children,smoker,region,charges
1358,1358,60.0,female,36.005,0,no,northeast,13228.84695
1359,1359,30.0,female,NaN,1,no,southwest,4149.73600
1360,1360,18.0,male,34.100,0,no,southeast,1137.01100
1361,1361,34.0,female,31.920,1,yes,northeast,37701.87680
1362,1362,37.0,male,28.025,2,no,northwest,6203.90175

Paso 5 conocemos la dimencion del datasets

In [10]:
print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

Cantidad de filas: 1363
Cantidad de columnas: 8

Paso 6 Analisis de la estructura del dataset

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1363 entries, 0 to 1362
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1363 non-null   int64
 1   age         1261 non-null   float64
 2   sex         1363 non-null   object
 3   bmi         1313 non-null   float64
 4   children    1363 non-null   int64
 5   smoker      1363 non-null   object
 6   region      1363 non-null   object
 7   charges     1363 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 85.3+ KB

Paso 7 Mostrar todos lo nombres de las columnas

In [15]:
print(df.columns)

Index(['Unnamed: 0', 'age', 'sex', 'bmi', 'children', 'smoker', 'region',
       'charges'],
      dtype='object')

Paso 8 Ahora verificamos el tipo de dato de cada Variable

In [16]:
print(df.dtypes)

Unnamed: 0      int64
age           float64
sex            object
bmi           float64
children        int64
smoker         object
region         object
charges       float64
dtype: object

Paso 9 Obtencion de estadisticas descriptivas

In [17]:
print(df.describe)

<bound method NDFrame.describe of       Unnamed: 0   age     sex     bmi  children smoker     region  \
0              0  19.0  female  27.900         0    yes  southwest
1              1  18.0    male  33.770         1     no         SE
2              2  28.0    male  33.000         3     no  southeast
3              3  33.0    male  22.705         0     no  northwest
4              4  32.0    male  28.880         0     no  northwest
...          ...   ...     ...     ...       ...    ...        ...
1358        1358  60.0  female  36.005         0     no  northeast
1359        1359  30.0  female     NaN         1     no  southwest
1360        1360  18.0    male  34.100         0     no  southeast
1361        1361  34.0  female  31.920         1    yes  northeast
1362        1362  37.0    male  28.025         2     no  northwest

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1358  13228.84695
1359   4149.73600
1360   1137.01100
1361  37701.87680
1362   6203.90175

[1363 rows x 8 columns]>

Paso 10 Analisis de las variables categoricas

In [18]:
df.describe(include="object")

         sex smoker     region
count   1363   1363       1363
unique     4      4          8
top     male     no  southeast
freq     653   1034        356

Paso 11 Buscamos los valores faltantes

In [19]:
df.isnull().sum()

Unnamed: 0      0
age           102
sex             0
bmi            50
children        0
smoker          0
region          0
charges         0
dtype: int64

Paso 12 Buscamos los registros duplicados

In [20]:
print("Cantidad de registros duplicados:", df.duplicated().sum())

Cantidad de registros duplicados: 0

Paso 13 Conteo de valores unicos

In [21]:
df.nunique()

Unnamed: 0    1363
age             47
sex              4
bmi            533
children         9
smoker           4
region           8
charges       1337
dtype: int64

Paso 14 visualizamos categorias disponibles

In [22]:
for columna in df.select_dtypes(include="object").columns:
    print("\n-----------------------------")
    print(columna)
    print(df[columna].unique())

-----------------------------
sex
['female' 'male' 'Female' 'Male']

-----------------------------
smoker
['yes' 'no' 'No' 'Yes']

-----------------------------
region
['southwest' 'SE' 'southeast' 'northwest' 'northeast' 'NE' 'SW' 'NW']

Paso 15 Frecuencia de cada categoria

In [24]:
for columna in df.select_dtypes(include="object").columns:
    print("\------")
    print("Columna:", columna)
    print(df[columna].value_counts())

\------
Columna: sex
sex
male      653
female    630
Female     43
Male       37
Name: count, dtype: int64
\------
Columna: smoker
smoker
no     1034
yes     268
No       50
Yes      11
Name: count, dtype: int64
\------
Columna: region
region
southeast    356
southwest    321
northwest    320
northeast    315
SE            16
NE            15
SW            10
NW            10
Name: count, dtype: int64

<>:2: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipykernel_6458/1387568137.py:2: SyntaxWarning: invalid escape sequence '\-'
  print("\------")